# Generated by Django 5.2.1 on 2025-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("litext_text", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textblock",
            name="text",
            field=models.CharField(),
        ),
    ]
