# Generated by Django 5.2.1 on 2025-05-23 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("litext_text", "0003_textblock_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextBlockLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("life_time", models.IntegerField(null=True)),
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="litext_text.textblock",
                    ),
                ),
            ],
        ),
    ]
