# Generated by Django 5.2.1 on 2025-05-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("litext_text", "0004_textblocklink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textblocklink",
            name="link",
            field=models.CharField(blank=True, unique=True),
        ),
    ]
